=== iceh2o/selenium/xsd/TestCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="com.mufg.ast">
    <xs:element name="testcase">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="case">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="step">
                                <xs:complexType>
                                    <!-- type of element from HTML page -->
                                    <xs:attribute name="type" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="url"/>
                                                <xs:enumeration value="input"/>
                                                <xs:enumeration value="checkbox"/>
                                                <xs:enumeration value="radio"/>
                                                <xs:enumeration value="form"/>
                                                <xs:enumeration value="pause"/>
                                                <xs:enumeration value="link"/>                                                    
                                                <xs:enumeration value="select"/>
                                                <xs:enumeration value="image"/>
                                                <xs:enumeration value="screen-capture"/>
                                                <xs:enumeration value="conf-capture"/>
                                                <xs:enumeration value="frame"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <!-- value of element -->
                                    <xs:attribute name="value"/>
                                    <xs:attribute name="id"/>
                                    <!-- select "by" element name, id or xpath -->
                                    <xs:attribute name="by"/>
                                    <!-- trim selected value? -->
                                    <xs:attribute default="true" name="trim">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="true"/>
                                                <xs:enumeration value="false"/>
                                            </xs:restriction>
                                        </xs:simpleType>                                                
                                    </xs:attribute>
                                    <!-- is element optional? Do we report error if we encounter error when process this element?" -->
                                    <xs:attribute name="reporterror" default="false">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="true"/>
                                                <xs:enumeration value="false"/>
                                            </xs:restriction>
                                        </xs:simpleType>                                                
                                    </xs:attribute>
                                    <!-- reference to another element by ID -->
                                    <xs:attribute name="ref"/>
                                    <!-- string value to do substring(chop_from, chop_to) -->
                                    <xs:attribute name="chopf"/>
                                    <!-- string value to do substring(chop_from, chop_to) -->
                                    <xs:attribute name="chopt"/>
                                    <!-- for element type select and checkbox, do we select by option value or visible value -->
                                    <xs:attribute name="optionvalue" default="false">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="true"/>
                                                <xs:enumeration value="false"/>
                                            </xs:restriction>
                                        </xs:simpleType>                                                                                        
                                    </xs:attribute>
                                    <xs:attribute name="description"/>
                                    <xs:attribute name="optional" default="false">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="true"/>
                                                <xs:enumeration value="false"/>
                                            </xs:restriction>
                                        </xs:simpleType>                                                                                                                
                                    </xs:attribute>
                                    <xs:attribute name="idx"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id"/>
                        <xs:attribute name="type"/>
                        <xs:attribute name="startTime"/>
                        <xs:attribute name="endTime"/>
                        <xs:attribute name="status"/>
                        <xs:attribute name="description"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="startTime"/>
            <xs:attribute name="endTime"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== iceh2o/selenium/TestCase_sso-tst.xml
<?xml version="1.0" encoding="UTF-8"?>
<testcase xmlns="com.mufg.ast" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TestCase.xsd">
    <case id="login" type="payment">
        <step type="url" value="https://sso-tst.unionbank.com/"/>
        <step type="input" by="id:userId" value="uswbuser1"/>
        <step type="image" by="xpath://img[@title='Next']"/>
        <step type="input" by="id:PASSWORD" value="UswDemo1"/>
        <step type="image" by="xpath://img[@title='Submit']"/>
        <step type="url" value="https://ina-tst.unionbank.com/s1gcb/portal/ssoLogon?APPLICATION_CONTEXT=ACH&amp;appId=AXW"/>
<!--        <step type="image" by="css:button.ub-dialog-window-close-link" optional="true"/>
        <step type="link" by="link:ACH"/>
        <step type="frame" by="index:0" optional="true"/>-->
        <step type="link" by="css:a.nav2selected"/>
        <step type="link" by="css:a[title='Create a New ACH Payment'"/>
        <step type="select" by="name:transactionType"  value="PPD - Prearranged Payment &amp; Deposit Entry"/>
        <step type="select" by="name:origAccount"  value="******1492 - USWB Demo Account 1"/>
        <step type="select" by="name:achCompanyId"  value="1212121212"/>
        <step type="input" by="name:companyEntryDesc" value="{today}"/>
        <step type="image" by="name:submit_addRecipientsFromList"/>
        <step type="checkbox" by="name:xactSelect" idx="0"/>
        <step type="image" by="name:submit_submit"/>
        <step type="image" by="name:submit_done"/>
        <step type="input" by="name:amountArray[0]" value="12.00"/>
        <step type="image" by="name:submit_preview"/>
        <step type="image" by="name:submit_submit"/>
    </case>
</testcase>

=== iceh2o/selenium/TestCase_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<testcase xmlns="com.mufg.ast" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TestCase.xsd">
    <case id="login" type="payment">
        <step type="url" value="https://nj7cbdmsitf2.btmna.com:9045/cbbtmu/logon/sbuser"/>
        <step type="input" by="name:companyID" value="100001"/>
        <step type="input" by="name:j_username" value="u000783"/>
        <step type="input" by="name:j_password" value="password_1"/>
        <step type="image" by="css:input[type='image']"/>        
        <step type="image" by="link:New Wire Payment"/>
        <step type="select" by="name:paymentType" value="label=BookWire"/>
        <step type="image" by="name:submit_continuePmt"/>
        <step type="input" by="name:debitAmount.value" value="10"/>
        <step type="select" by="name:debitAccount" value="label=Checking 1 -- 0310027764 -- USD -- N/A"/>
        <step type="input" by="name:detailsOfPayment1" value="mike e"/>
        <step type="input" by="name:detailsOfPayment2" value="add1"/>
        <step type="input" by="name:detailsOfPayment3" value="add2"/>
        <step type="select" by="name:benfIdType" value="label=Account Number"/>
        <step type="input" by="name:benfId" value="1234567890"/>
        <step type="input" by="name:benefeciaryName" value="mike 3"/>
        <step type="input" by="name:benfAddr1" value="add1"/>
        <step type="input" by="name:benfAddr2" value="add2"/>
        <step type="select" by="name:benefPersonalBankId" value="label=YASHIRONI NASH--026009632--ABA (Wire)"/>        
        <step type="image" by="name:submit_preview"/>
    </case>
</testcase>

=== iceh2o/selenium/TestCase-Payments-Approval.xml
<?xml version="1.0" encoding="UTF-8"?>
<testcase xmlns="com.mufg.ast" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          endTime="Tue Jul 19 12:38:40 EDT 2016" 
          startTime="Tue Jul 19 12:02:32 EDT 2016" xsi:schemaLocation="TestCase.xsd">
    <case 
        endTime="Tue Jul 19 12:03:05 EDT 2016" id="login" 
        startTime="Tue Jul 19 12:02:32 EDT 2016" 
         
        type="login">
        <step type="url" value="https://nj7cbdmsitf2.btmna.com:9045/cbbtmu/logon/sbuser"/>
        <step by="name:companyID" type="input" value="100090"/>
        <step by="name:j_username" type="input" value="u000783a"/>
        <!-- <step type="pause"  value="10" highlight="name:j_password"/>  -->          
        <step by="name:j_password" type="pause"/> 
        <step by="name:sbLogonForm" type="form"/>
    </case>
    <case endTime="Tue Jul 19 12:05:08 EDT 2016" id="INTWIRE-TEMPLATES-01-01" startTime="Tue Jul 19 12:03:05 EDT 2016"  type="payment">
        <step by="text:PAYMENTS" type="link"/>
        <step by="text:Wires" type="link"/>
        <step by="text:New Wire Payment" type="link"/>        
        <step by="name:templateType" type="select" value="SWIFT FC JPY 1 - Mike e - 0090766502 - JPY"/>        
        <step by="name:submit_continueTemplatePayment" type="image"/>
        <!-- Payment Information                                                                    -->
        <step by="name:contractNumber" type="input" value=""/>
        <step by="name:creditAmount.value" type="input" value="100"/>
        <step by="name:contractRate" type="input" value=""/>
        <step by="name:detailsOfPayment1" type="input" value=""/>
        <step by="name:detailsOfPayment2" type="input" value=""/>
        <step by="name:detailsOfPayment3" type="input" value=""/>
        <step by="name:detailsOfPayment4" type="input" value=""/>
        <!-- Additional Routing Information (Optional)             -->
        <!--
        <step type="select" by="name:receiverInfo1" value="/CHEQUE/"/>
        <step type="input"  by="name:receiveCodeDescription1" value=""/>
        <step type="select" by="name:receiverInfo2" value="/CHEQUE/"/>
        <step type="input"  by="name:receiveCodeDescription2" value=""/>
        <step type="select" by="name:receiverInfo3" value="/CHEQUE/"/>
        <step type="input"  by="name:receiveCodeDescription3" value=""/>
        <step type="select" by="name:receiverInfo4" value="/CHEQUE/"/>
        <step type="input"  by="name:receiveCodeDescription4" value=""/>
        -->
        
        <!-- Payment Schedule                                      -->
        <step by="name:submit_calculateValueDate" type="image"/>
        <!--
        <step type="input"  by="name:effectiveDate" value="{today}"/>
        -->
        <!-- radio value are finite | indefinite | enddate  -->
        <step by="name:recurrenceDuration" type="radio" value="finite"/>
        <!--
        <step type="input"  by="name:endDate" value="08/14/2016"/>
        -->
        
        <!-- Options                                                    -->
        <!-- radio value are save | approveOnSubmit  -->
        <step by="name:approvalType" type="radio" value="save"/>
        <step by="name:submit_preview" type="image"/>
        <step type="screen-capture"/>
        <step by="name:submit_submit" type="image"/>
        <step by="id:msgBlockSuccess-successText" chopf="Sequence Number:" chopt="Payment Type" id="seqNum0101" type="conf-capture" value=" 2388011&#10;    "/>
        <step type="screen-capture"/>
        <step by="xpath://img[contains(@src,'/images/icn_exit.gif')]" type="image"/>
        <step by="id:btnLogout" reporterror="false" type="image"/>

        
        <step by="name:companyID" type="input" value="100090"/>
        <step by="name:j_username" type="input" value="u000783"/>
        <!-- <step type="pause"  value="10" highlight="name:j_password"/>  -->          
        <step by="name:j_password" pause="true" type="input" value="tmppass_00"/> 
        <step by="name:sbLogonForm" type="form"/>
        <step by="name:sequenceNumber" ref="seqNum0101" type="input"/>
        <step by="name:submit_entry" type="image"/>
        <step by="name:xactSelect" type="checkbox" value="0"/>
        <step by="name:submit_approve" type="image"/>
        <step by="name:submit_approve" type="image"/>
    </case>
    <case endTime="Tue Jul 19 12:38:40 EDT 2016" id="logout" startTime="Tue Jul 19 12:38:39 EDT 2016"  type="logout">
        <step by="xpath://img[contains(@src,'/images/icn_exit.gif')]" type="image"/>
        <step by="id:btnLogout" reporterror="false" type="image"/>
    </case>   
</testcase>
